;;; nalist-test.el --- Tests for nalist

(defun setup-alist ()
  (setq al '((a . b) (c . d)))
  (setq al-eql '((1 . a) (1.0 . b)))
  (setq al-equal '(("spam" . 3) ((a (b c)) . d))))

(ert-deftest test-gcache-alist-subset-p ()
  (should (eq (gcache-alist-subset-p '((a . 1)) '((b . 2) (a . 1)))
              t)))

(ert-deftest test-gcache-alist-equal ()
  (should (eq (gcache-alist-set-equal '((a . 1) (b . 2))
                                      '((b . 2) (a . 1)))
              t)))

(ert-deftest test-gcache-alist-clear ()
  (setup-alist)
  (gcache-alist-clear al)
  (should (eq al nil)))

(ert-deftest test-gcache-alist-get ()
  (setup-alist)
  (should (eq (gcache-alist-get 'a al)
              'b))
  (should (eq (gcache-alist-get 'b al)
              nil))
  (should (eq (gcache-alist-get 'c al)
              'd))
  (should (eq (gcache-alist-get 'a al :testfn 'eq)
              'b))
  (should (eq (gcache-alist-get 'b al :testfn 'eq)
              nil))
  (should (eq (gcache-alist-get 1 al-eql)
              'a))
  (should (eq (gcache-alist-get 1 al-eql :testfn 'eql)
              'a))
  (should (eq (gcache-alist-get 1.0 al-eql)
              nil))
  (should (eq (gcache-alist-get 1.0 al-eql :testfn 'eql)
              'b))
  (should (eq (gcache-alist-get "spam" al-equal :testfn 'equal)
              3))
  (should (eq (gcache-alist-get '(a (b c)) al-equal :testfn 'equal)
              'd))
  (should (eq (gcache-alist-get "Hi" al-equal :testfn #'(lambda (x y) (= (length x) (length y))))
              'd))
  (should (eq (gcache-alist-get 'a al :default 'no-value)
              'b))
  (should (eq (gcache-alist-get 'f al :default 'no-value)
              'no-value)))

(ert-deftest test-gcache-alist-set ()
  (setup-alist)
  (gcache-alist-set 'e 'f al)
  (should (gcache-alist-set-equal al '((a . b) (c . d) (e . f))))
  (gcache-alist-set 'c 'g al)
  (should (gcache-alist-set-equal al '((a . b) (c . g) (e . f))))
  )

(ert-deftest test-gcache-alist-remove ()
  (setup-alist)
  (gcache-alist-remove 'a al)
  (should (gcache-alist-set-equal al '((c . d))))
  )

;; Local Variables:
;; flycheck-disabled-checkers: (emacs-lisp-checkdoc)
;; End:

;;; nalist-test.el ends here
